### ISSUE TITLE
Improve halo2 query calls

### ISSUE THREAD

**Issue by Brechtpd** [taikoxyz/zkevm-circuits#61]
https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1115#issuecomment-1415986963

**Comment by Brechtpd** [comment]
Possible approach:

- `FixedQuery`, `AdviceQuery`, and `InstanceQuery` are modified to have the `index` field as `Option<usize>`.

- In `Column` add helper function to query cells, with the most general one doing something like this:
```
    pub fn query_cell<F: Field>(&self, at: Rotation) -> Expression<F> {
        Expression::Advice(AdviceQuery {
            index: None,
            column_index: self.index,
            rotation: at,
            phase,
        })
    }
```
Also add functions like `expr()`, `next()`, `prev()` which will be often used variants.
-  In halo2, in the `create_gate` function, run over all expressions and set the correct index for expressions that still have their `index` set to `None` (using the same code as normally done by `query_advice`/`query_fixed`/`query_index`).

Small downside of this approach: needs an `unwrap` every time `index` is used in the prover. But this operations should practically be free so should be fine I think. The alternatives like using a special value for `index` to mark it as not yet set, or trying to move `index` outside of the struct it's currently in seems more troublesome.

**Comment by CeciliaZ030** [comment]
Another way to solve this:

- `VirtualCell<VirtualCells<'a, F: Field>` exists because it holds a reference to `meta: &'a mut ConstraintSystem<F>`. It pushes cell (column, at) into ConstraintSystem whenever query is made. You may agree that VirtualCell is pretty redundant. 
- We can put `meta: &'a mut ConstraintSystem<F>` into `Column` so that we can make side effects on ConstraintSystem directly when `Column` is queried like this `col.query_at(Rotation::cur())`
``` 
pub struct Column<'a, F: Field, C: ColumnType> {
    meta: &'a mut ConstraintSystem<F>,
    index: usize,
    column_type: C,
}
```
Having a reference of the meta structure on each column will give greater flexibilities to add different APIs, but we gotta change a large amount of code :(

**Comment by CeciliaZ030** [comment]
> Small downside of this approach: needs an unwrap every time index is used in the prover. But this operations should practically be free so should be fine I think. 

Agree. I was trying to do it by ignoring the index first but I realized that we need to recursively get the leaf of the Expression tree to get the `FixedQuery`, `AdviceQuery`, `Selector`, etc.
This looks ugly to me because we are building the tree button-up in the closure and now we are going over again top-down at the end of  `create_gate`.

**Comment by Brechtpd** [comment]
> Having a reference of the meta structure on each column will give greater flexibilities to add different APIs, but we gotta change a large amount of code :(

Would having the mutable reference there not also complicate how we can store columns. Columns are often copied around where needed which seems complicated when making them more than simple data objects.

> This looks ugly to me because we are building the tree button-up in the closure and now we are going over again top-down at the end of create_gate.

Seems fine to me to be honest. Expressions are a tree just because it's an elegant way to represent and build them, nothing more. So if we want to manipulate expressions we just what needs to be done, it's not like things like the performance or something is important for these things. If it's simple it's good.
